---
# tasks file for hswong3i.cachefilesd

- name: apt-get install
  apt:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items:
    - { state: "latest", name: "cachefilesd" }
  notify: restart cachefilesd
  tags: hswong3i.cachefilesd

- name: copy templates
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - { src: "etc/default/cachefilesd.j2", dest: "/etc/default/cachefilesd", owner: "root", group: "root", mode: "0644" }
    - { src: "etc/cachefilesd.conf.j2", dest: "/etc/cachefilesd.conf", owner: "root", group: "root", mode: "0644" }
  notify: restart cachefilesd
  tags: hswong3i.cachefilesd

- name: enable service
  service:
    name: "cachefilesd"
    enabled: "yes"
  notify: restart cachefilesd
  tags: hswong3i.cachefilesd
